-- Fix Services Table Schema (Version 2 - Complete)
-- Run this in Supabase SQL Editor

-- 1. Drop the old table to start fresh
DROP TABLE IF EXISTS services;

-- 2. Create the new table with ALL columns matching the Frontend Code
create table services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text[] default '{}', -- Stores array of strings
  role text,
  icon text,
  
  -- Primary Action
  action_type text default 'link',
  action_text text,
  action_url text,
  modal_id text,
  
  -- Secondary Action (Missing in previous version)
  secondary_action_text text,
  secondary_action_type text default 'link',
  secondary_action_url text,
  secondary_modal_id text,
  
  "order" integer default 0,
  tag text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Security
alter table services enable row level security;

-- 4. Add Policies (Allow everyone to read/write for this demo)
create policy "Public read services" on services for select using (true);
create policy "Anon full access services" on services for all using (true) with check (true);
