-- Full Schema for Mini App Oleg
-- Run this in Supabase SQL Editor

-- 1. App Settings (Stores global texts and configurations)
create table if not exists app_settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Links (Stores social links and other external URLs)
create table if not exists links (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  icon text,
  type text default 'external',
  is_active boolean default true,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Audit Logs (Stores admin actions)
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Services (Stores services offered)
create table if not exists services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price text,
  icon text,
  action_type text default 'link',
  action_value text,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Cases (Stores portfolio cases)
create table if not exists cases (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  details text,
  link text,
  icon text,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Announcements (Stores news and updates)
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  tag text,
  title text not null,
  description text,
  date text,
  urgent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on all tables
alter table app_settings enable row level security;
alter table links enable row level security;
alter table audit_logs enable row level security;
alter table services enable row level security;
alter table cases enable row level security;
alter table announcements enable row level security;

-- Policies: Allow public read and full access for anonymous users (for this specific app setup)
-- Note: In a production app with auth, you would restrict write access.

-- App Settings
create policy "Public read settings" on app_settings for select using (true);
create policy "Anon full access settings" on app_settings for all using (true) with check (true);

-- Links
create policy "Public read links" on links for select using (true);
create policy "Anon full access links" on links for all using (true) with check (true);

-- Services
create policy "Public read services" on services for select using (true);
create policy "Anon full access services" on services for all using (true) with check (true);

-- Cases
create policy "Public read cases" on cases for select using (true);
create policy "Anon full access cases" on cases for all using (true) with check (true);

-- Announcements
create policy "Public read announcements" on announcements for select using (true);
create policy "Anon full access announcements" on announcements for all using (true) with check (true);

-- Audit Logs
create policy "Anon read logs" on audit_logs for select using (true);
create policy "Anon insert logs" on audit_logs for insert with check (true);

-- Seed Default Settings
insert into app_settings (key, value) values
('site_title', 'Олег Ивченко'),
('site_description', 'Предприниматель, CEO, инвестор'),
('home_bio_1', 'Я предприниматель, который из возможностей делает работающие бизнесы. Я хаб, где сходятся идеи, ресурсы и люди. Я отбираю лучшие из множества проектов, анализирую их, привлекаю деньги, исполнителей и партнеров и вместе мы ставим бизнес на рельсы.'),
('home_bio_2', 'Уникальность моей работы — постоянная воронка возможностей и умение реализовывать их в партнерстве. В этом приложении — мои действующие бизнесы и точка входа для новых совместных проектов.'),
('stat_contacts', '9000+'),
('stat_projects', '40'),
('stat_deals', '1300+'),
('stat_turnover', '3.5 млрд'),
('btn_share', 'Поделиться визиткой'),
('btn_apply', 'Оставить заявку'),
('share_message', 'Предприниматель, Инвестор. Контакты и проекты.'),
('contact_title', 'Контакты'),
('contact_subtitle', 'Всегда на связи для партнеров'),
('contact_tg_channel', '@ivchenkooleg'),
('contact_tg_channel_url', 'https://t.me/ivchenkooleg'),
('contact_tg_personal', '@oleg8383'),
('contact_tg_personal_url', 'https://t.me/oleg8383'),
('contact_email', 'oleg@ivchenko.pro'),
('contact_email_url', 'mailto:oleg@ivchenko.pro')
on conflict (key) do nothing;
