-- 1. Table for App Settings (Theme, SEO, etc.)
create table app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for Links Management
create table links (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  icon text, -- Icon name from Lucide
  type text default 'external', -- 'internal', 'external'
  is_active boolean default true,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table for Audit Logs
create table audit_logs (
  id bigint generated by default as identity primary key,
  action text not null, -- 'create', 'update', 'delete', 'login'
  entity text not null, -- 'announcement', 'settings', 'link', 'auth'
  details text, -- Simple text description
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table app_settings enable row level security;
alter table links enable row level security;
alter table audit_logs enable row level security;

-- 5. Policies (Allow public read for settings/links, allow anon write for Admin)
-- Settings
create policy "Public read settings" on app_settings for select using (true);
create policy "Anon full access settings" on app_settings for all using (true) with check (true);

-- Links
create policy "Public read links" on links for select using (true);
create policy "Anon full access links" on links for all using (true) with check (true);

-- Logs
create policy "Anon read logs" on audit_logs for select using (true);
create policy "Anon insert logs" on audit_logs for insert with check (true);
