-- 1. Create the table
create table announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tag text not null,
  date text not null,
  urgent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table announcements enable row level security;

-- 3. Create a policy that allows all operations (Select, Insert, Update, Delete)
-- Note: In a production environment with real Supabase Auth, you would restrict this.
-- Since we are using a simple frontend password ("6789"), we allow the Anon Key to perform operations.
create policy "Enable all access for anon key" 
on announcements 
for all 
using (true) 
with check (true);
